### ISSUE TITLE
Add License for this Repository

### ISSUE THREAD

**Issue by mnafian** [brucetoo/GradientTabStrip#2]
Hi, I do not see a license choice for this repository.

I note that https://github.com/brucetoo/GradientTabStrip/ repository must be contains at least Apache license for good enough to open source project.

While that is a good choice for some projects, Thank you.

[EDIT], I didn't see your license because it is not in the master branch, you must be move the license  info on master branch to get the user get more clearly info.

**Comment by brucetoo** [comment]
Thanks your remind.
