### ISSUE TITLE
Problem with Gradient

### ISSUE THREAD

**Issue by tuanth89** [brucetoo/GradientTabStrip#3]
Firstly, thank for awesome. i realy like and used to my project :)
I have a problem when swipe fast and holding, last gradient textview not set color default completely as below
![15174566_1188288181278402_1756529002_n](https://cloud.githubusercontent.com/assets/11812307/20510294/cac12d2a-b0a1-11e6-890a-097b210d88d2.png)

Which way to resolve this ?
Thank you

**Comment by brucetoo** [comment]
I will check later。

**Comment by tuanth89** [comment]
Thanks :)

**Comment by brucetoo** [comment]
Please check out [this commit](https://github.com/brucetoo/GradientTabStrip/commit/96aeaeddcc335863449bc6f6b96c027c2d806149) .

**Comment by tuanth89** [comment]
woa, thank you so much!
Work like a charm :)
Closed
